### ISSUE TITLE
BridgefyException class is unable to cast SocketTimeoutException 

### ISSUE THREAD

**Issue by Anees-Iqbal** [bridgefy/bridgefy-android-samples#23] opened 2020-11-10 21:30 UTC
I have received a ClassCastException with SocketTimeoutException. Also there is issue reported to my Firebase Console related to Java reactive streams. Logs are attached as follows,

```
Caused by java.lang.ClassCastException
java.net.SocketTimeoutException cannot be cast to com.bridgefy.sdk.client.BridgefyException
Caused by java.lang.ClassCastException: java.net.SocketTimeoutException cannot be cast to com.bridgefy.sdk.client.BridgefyException
       at com.bridgefy.sdk.framework.controller.Analytics$NetworkJobService$1$1.onError(SourceFile:226)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```

Along with this fatal exception as: 

```

Fatal Exception: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.SocketTimeoutException cannot be cast to com.bridgefy.sdk.client.BridgefyException
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:121)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by kekoyde** [comment] 2020-11-10 22:21
Hi @Anees-Iqbal, 
Thanks for reporting this error, a bad casting was detected, the cause of the error is the client update token our server, don't worry, the token is updated automatically.
This issue is resolved in version **1.1.28**

Thank you for using Bridgefy.

**Closed by kekoyde** 2020-11-10 22:21 UTC
